name: pub_cache
version: 0.3.0
description: A library to reflect on the local pub cache.
homepage: https://github.com/google/pub_cache

environment:
  sdk: '>=2.0.0 <2.12.0'

dependencies:
  path: ^1.6.1
  pub_semver: ^1.4.4
  yaml: ^2.1.15

dev_dependencies:
  test: ^1.3.0
